# Generated by Django 4.2.3 on 2023-07-31 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solds', '0001_initial'),
        ('disease', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solditem',
            name='pharmacist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solditem',
            name='sold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to='solds.sold'),
        ),
        migrations.AddField(
            model_name='sold',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.disease'),
        ),
        migrations.AddField(
            model_name='sold',
            name='pharmacist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
