# Generated by Django 4.2.3 on 2023-07-31 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('disease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='disease.disease')),
                ('medicine', models.ManyToManyField(to='medicine.medicine')),
            ],
        ),
    ]
