# Generated by Django 4.2.3 on 2023-08-05 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_alter_medicine_solds_count'),
        ('banlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, blank=True, null=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medicine.category')),
                ('medicine', models.ManyToManyField(to='medicine.medicine')),
            ],
        ),
    ]
