# Generated by Django 4.2.3 on 2023-08-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banlist', '0003_alter_dangerlist_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountSaleDanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
